name = "SignalDetectionModels"
uuid = "1177497a-bfcb-4701-b32d-ffcd4fa2eaa8"
version = "0.1.0"
authors = ["itsdfish"]

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[weakdeps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
PlotsExt = "Plots"

[compat]
ArgCheck = "2.5.0"
Distributions = "0.25.122"
Plots = "1.41.2"
Random = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
